INSERT INTO multimedia.generos
VALUES 	(NULL, "Ciencia Ficcion"),
		(NULL, "Fantasia"),
        (NULL, "Drama"),
		(NULL, "Ficcion"),
        (NULL, "Sucesos"),
		(NULL, "Misterio"),
        (NULL, "Hechos veridicos"),
		(NULL, "Crimen"),
        (NULL, "Suspenso"),
		(NULL, "Aventura"),
        (NULL, "Sci-Fi"),
		(NULL, "Accion"),
        (NULL, "Comedia"),
		(NULL, "Familia"),
        (NULL, "Western"),
		(NULL, "Tecnologia"),
        (NULL, "Terror"),
		(NULL, "Historia"),
        (NULL, "Intriga")
        ;